apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: react-k8s-com-tls
spec:
  secretName: react-k8s-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: react-k8s.com
  dnsNames:
    - react-k8s.com
    - www.react-k8s.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - react-k8s.com
          - www.react-k8s.com